/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-04 06:52:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/ahj/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/ahj/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/ahj/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668994699115L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<title>Main</title>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/head.jsp", out, false);
      out.write("\n");
      out.write("	<style>\n");
      out.write("		        html,\n");
      out.write("        body {\n");
      out.write("          position: relative;\n");
      out.write("          height: 100%;\n");
      out.write("        }\n");
      out.write("  \n");
      out.write("        body {\n");
      out.write("          background: #eee;\n");
      out.write("          font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\n");
      out.write("          font-size: 14px;\n");
      out.write("          color: #000;\n");
      out.write("          margin: 0;\n");
      out.write("          padding: 0;\n");
      out.write("        }\n");
      out.write("  \n");
      out.write("        .swiper {\n");
      out.write("          width: 100%;\n");
      out.write("          height: 50%;\n");
      out.write("        }\n");
      out.write("  \n");
      out.write("        .swiper-slide {\n");
      out.write("          text-align: center;\n");
      out.write("          font-size: 18px;\n");
      out.write("          background: #fff;\n");
      out.write("  \n");
      out.write("          /* Center slide text vertically */\n");
      out.write("          display: -webkit-box;\n");
      out.write("          display: -ms-flexbox;\n");
      out.write("          display: -webkit-flex;\n");
      out.write("          display: flex;\n");
      out.write("          -webkit-box-pack: center;\n");
      out.write("          -ms-flex-pack: center;\n");
      out.write("          -webkit-justify-content: center;\n");
      out.write("          justify-content: center;\n");
      out.write("          -webkit-box-align: center;\n");
      out.write("          -ms-flex-align: center;\n");
      out.write("          -webkit-align-items: center;\n");
      out.write("          align-items: center;\n");
      out.write("        }\n");
      out.write("  \n");
      out.write("        .swiper-slide img {\n");
      out.write("          display: block;\n");
      out.write("          object-fit: cover;\n");
      out.write("          background-size: contain;\n");
      out.write("        }\n");
      out.write("        .simg{\n");
      out.write("            background-image: url(\"resources/img/wrap_bg1.jpg\");\n");
      out.write("        }\n");
      out.write("        .s-title {\n");
      out.write("            text-align: left;\n");
      out.write("            color: #FEFEFE;\n");
      out.write("            padding-left: 2rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        .s-title:after {\n");
      out.write("        content: \"\";\n");
      out.write("        display: block;\n");
      out.write("        width: 90%;\n");
      out.write("        border-bottom: 1px solid #bcbcbc;\n");
      out.write("        margin-top: 10%;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .eimg{\n");
      out.write("        width: 100%;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .card-title { text-align: center; font-size: 20px; font-weight: 700;}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- TODO Main -->\n");
      out.write("	<div class=\"wrap\">\n");
      out.write("		<!-- TODO header -->\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\n");
      out.write("		<!-- TODO content -->\n");
      out.write("        <div class=\"container px-4 px-lg-5 nimg\">\n");
      out.write("            <!-- Swiper -->\n");
      out.write("            <div class=\"swiper mySwiper\">\n");
      out.write("                <div class=\"swiper-wrapper\">\n");
      out.write("                <div class=\"swiper-slide simg\">\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <h2 class=\"s-title\">안녕나의 이웃3<br>탈북민 리얼 취업 성공기</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <img src=\"resources/img/s1.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-slide simg\">\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <h2 class=\"s-title\">2022 통일로가요<br>수상곡 듣기</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <img src=\"resources/img/s2.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-slide simg\">\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <h2 class=\"s-title\">「비핵·평화·번영의 한반도」윤석열 정부 통일·대북정책 설명자료 발간</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <img src=\"resources/img/s3.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-slide simg\">\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <h2 class=\"s-title\">비핵·평화·번영의 한반도를 위한 담대한 구상</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <img src=\"resources/img/s4.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-slide simg\">\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <h2 class=\"s-title\">소원이가 전하는 할머니, 할아버지 이야기</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <img src=\"resources/img/s5.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-pagination\"></div>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("            <!-- Initialize Swiper -->\n");
      out.write("            <script>\n");
      out.write("                var swiper = new Swiper(\".mySwiper\", {\n");
      out.write("                spaceBetween: 30,\n");
      out.write("                centeredSlides: true,\n");
      out.write("                autoplay: {\n");
      out.write("                    delay: 2500,\n");
      out.write("                    disableOnInteraction: false,\n");
      out.write("                },\n");
      out.write("                pagination: {\n");
      out.write("                    el: \".swiper-pagination\",\n");
      out.write("                    clickable: true,\n");
      out.write("                },\n");
      out.write("                navigation: {\n");
      out.write("                    nextEl: \".swiper-button-next\",\n");
      out.write("                    prevEl: \".swiper-button-prev\",\n");
      out.write("                },\n");
      out.write("                });\n");
      out.write("            </script>\n");
      out.write("            \n");
      out.write("            <!-- Heading Row-->\n");
      out.write("            <div class=\"row gx-4 gx-lg-5 align-items-center my-5 nimg\">\n");
      out.write("                <div class=\"col-lg-5\"><img class=\"img-fluid rounded mb-4 mb-lg-0\"\n");
      out.write("                        src=\"resources/img/C2.png\" alt=\"...\" /></div>\n");
      out.write("                <div class=\"col-lg-7\">\n");
      out.write("                    <table class=\"table\">\n");
      out.write("                        <thead>\n");
      out.write("                          <tr>\n");
      out.write("                            <th scope=\"col\">공지사항</th>\n");
      out.write("                          </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                          <tr>\n");
      out.write("                            <td>무주택 전후납북피해자 대상 기관추천 특별공급 안내(남양주진접2지구)</td>\n");
      out.write("                            <td>2023-01-03</td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr>\n");
      out.write("                            <td>무주택 전후납북피해자 대상 기관추천 특별공급 안내(인천 주안 더샵 아르테)</td>\n");
      out.write("                            <td>2023-01-03</td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr>\n");
      out.write("                            <td>「인천통일+센터 청년 서포터즈」선발 최종 합격자 공고</td>\n");
      out.write("                            <td>2023-01-03</td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr>\n");
      out.write("                            <td>2023년 통일교육 선도대학 모집 공고문</td>\n");
      out.write("                            <td>2023-01-03</td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr>\n");
      out.write("                            <td>남북교류협력법 시행령 개정 입법예고</td>\n");
      out.write("                            <td>2023-01-03</td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr>\n");
      out.write("                            <td>’23. 1학기「대학생을 위한 통일 특강 및 강좌」선정결과 발표</td>\n");
      out.write("                            <td>2023-01-03</td>\n");
      out.write("                          </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                      </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Content Row-->\n");
      out.write("            <div class=\"row gx-4 gx-lg-5 nimg\">\n");
      out.write("                <div class=\"col-md-4 mb-5\">\n");
      out.write("                    <div class=\"card h-100\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <h2 class=\"card-title\">통일 이야기</h2>\n");
      out.write("                            <img src=\"resources/img/e1.jpg\" alt=\"\" class=\"eimg\">\n");
      out.write("                        </div>\n");
      out.write("                       \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 mb-5\">\n");
      out.write("                    <div class=\"card h-100\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <h2 class=\"card-title\">통일 이야기</h2>\n");
      out.write("                            <img src=\"resources/img/e2.png\" alt=\"\" class=\"eimg\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 mb-5\">\n");
      out.write("                    <div class=\"card h-100\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <h2 class=\"card-title\">알림판</h2>\n");
      out.write("                            <img src=\"resources/img/e3.jpg\" alt=\"\" class=\"eimg\">\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("		<!-- TODO footer -->\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<!-- /Main -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/home.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
